### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by BMchris0200** [huliangxiao/GaussianAvatar#1]
It's a very impressive work which really attracts me.
I wonder when will the code be released as I have academic work on similar topics.

**Comment by Zebraslive** [comment]
> It's a very impressive work which really attracts me. I wonder when will the code be released as I have academic work on similar topics.

The world isn't ready for this yet. But I am.

**Comment by huliangxiao** [comment]
Thanks! I'm working on getting my code ready for release, possibly by next month.

**Comment by oranges01** [comment]
When will the code be released, please

**Comment by gjgjgjfff** [comment]
+1

**Comment by Inferencer** [comment]
while you guys wait there is another gaussian avatar just released code today
https://neuralbodies.github.io/3DGS-Avatar/index.html
