### ISSUE TITLE
Missed mask images in dynvideo_female sequence

### ISSUE THREAD

**Issue by tgeonho** [huliangxiao/GaussianAvatar#11]
Hi, thanks for your great work!

I would like to train the model with 'dynvideo_female' sequence. But, in the train split, the number of mask images is fewer than the number of rgb images.
Could I get the full mask images?

Best regards,

**Comment by LinzhouLi** [comment]
I encountered the same issue. It seems to be caused by the discrepancy in file naming between ‘mask’ and 'image'. Both folders contain 778 images, but the images in the 'mask' folder are named sequentially, while those in the 'image' folder are not.

**Comment by huliangxiao** [comment]
Sorry for the incomplete data.
I'm going to update the data, by the way, any human foreground segmentation tool will work fine for processing the data such as (RVM)[https://github.com/PeterL1n/RobustVideoMatting].

**Comment by tgeonho** [comment]
Thanks!
