### ISSUE TITLE
how to obtain the "query_posemap_512_cano_smpl.npz" and "smpl_cano_joint_mat.pth" for new training data?

### ISSUE THREAD

**Issue by xiezhy6** [huliangxiao/GaussianAvatar#2]
Hi, thanks for sharing the code of the excellent work!

In the provided data, I found only the data for "m4c_processed" can be directly used by the code. 

It seems that the some files (e.g., "query_posemap_512_cano_smpl.npz" and "smpl_cano_joint_mat.pth") are missed for the other training data.

How could we generate this two files?

Thanks a lot a lot!

**Comment by huliangxiao** [comment]
I am working on releasing the processing scripts by next week.
"query_posemap_512_cano_smpl.npz" is the rendered canonical SMPL/SMPL-X UV position map, codes derived from [SCALE](https://github.com/qianlim/SCALE/tree/main/lib_data).
 "smpl_cano_joint_mat.pth" is the joint mat of the canonical SMPL/SMPL-X model, the output [A](https://github.com/huliangxiao/GaussianAvatar/blob/5be993e7c9c15fcc70149d22d60ef5d51af2a478/submodules/smplx/body_models.py#L391) of SMPL/SMPL-X forward function.
