### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by kihoon96** [huliangxiao/GaussianAvatar#3]
Thank you for sharing your excellent work!
I wonder how to run this work on my own data.
How should I preprocess the data for training?
For example, how do I preprocessed the data to make smpl_cano_joint_mat.pth, query_posemap_512_cano_smpl.npz, etcs.
Many thanks!

**Comment by huliangxiao** [comment]
Hi! I have uploaded the script.
`cd scripts` and run `python gen_pose_map_cano_smpl.py`.
Sincerely.

**Comment by kihoon96** [comment]
Thank you so much!

**Comment by R132** [comment]
Anyone knows how to process the data on server without DISPLAY windows?

**Comment by R132** [comment]
> Anyone knows how to process the data on server without DISPLAY windows?

I got error with :   freeglut (foo): failed to open display ''

**Comment by kihoon96** [comment]
> n

Also tried with X window ssh but got opengl BAD ALLOC error. For now, I just processed with my local PC which has monitor.

**Comment by kihoon96** [comment]
> > Anyone knows how to process the data on server without DISPLAY windows?
> 
> I got error with : freeglut (foo): failed to open display ''


n

Also tried with X window ssh but got opengl BAD ALLOC error. For now, I just processed with my local PC which has monitor.

**Comment by R132** [comment]
> > > Anyone knows how to process the data on server without DISPLAY windows?
> > 
> > 
> > I got error with : freeglut (foo): failed to open display ''
> 
> Also tried with X window ssh but got opengl BAD ALLOC error. For now, I just processed with my local PC which has monitor.

Facing "Attempt to call an undefined function glutInit" on PC(win 10)， seems to be the mismatch of 32bit build and 64bit. Google says unofficial x64 builds could be found on "https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl", which is out of date now. Any suggestion?

**Comment by R132** [comment]
https://download.csdn.net/download/weixin_40850758/12418372?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522170702695116800226522754%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=170702695116800226522754&biz_id=1&utm_medium=distribute.pc_search_result.none-task-download-2~all~first_rank_ecpm_v1~rank_v31_ecpm-2-12418372-null-null.142^v99^pc_search_result_base6&utm_term=pyopengl-3.1.5-win_amd64.whl&spm=1018.2226.3001.4187.3

**Comment by NagabhushanSN24** [comment]
How do I run this on headless ubuntu server? I'm getting the same `failed to open display` error. If I run with `xvfb` as 
```
xvfb-run -a python gen_pose_map_cano_smpl.py
```
I get the below error (I have `pyopengl` version `3.1.1a1` installed) 
```
saving obj...
torch.Size([1, 24, 4, 4])
saving pose_map 512 ...
Compilation failure for vertex shader:
b'0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Compilation failure for fragment shader:
b'0:1(10): error: GLSL 4.10 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'
Linker failure: 
b'error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader'
Traceback (most recent call last):
  File "gen_pose_map_cano_smpl.py", line 112, in <module>
    save_npz(smplx_parm_path, 512)
  File "gen_pose_map_cano_smpl.py", line 94, in save_npz
    posmap512, _, _ = render_posmap(body_mesh.vertices, body_mesh.faces, uvs, faces_uvs, img_size=512)
  File "gen_pose_map_cano_smpl.py", line 27, in render_posmap
    rndr = PosRender(width=img_size, height=img_size)
  File ".../GaussianAvatar/scripts/posmap_generator/lib/renderer/gl/pos_render.py", line 9, in __init__
    CamRender.__init__(self, width, height, name, program_files=['pos_uv.vs', 'pos_uv.fs'])
  File ".../GaussianAvatar/scripts/posmap_generator/lib/renderer/gl/cam_render.py", line 9, in __init__
    Render.__init__(self, width, height, name, program_files, color_size)
  File ".../GaussianAvatar/scripts/posmap_generator/lib/renderer/gl/render.py", line 49, in __init__
    self.model_mat_unif = glGetUniformLocation(self.program, 'ModelMat')
  File ".../anaconda3/envs/GaussianAvatar2/lib/python3.8/site-packages/OpenGL/latebind.py", line 61, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File ".../anaconda3/envs/GaussianAvatar2/lib/python3.8/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 387, in glGetUniformLocation
    return baseOperation( program, name )
  File ".../anaconda3/envs/GaussianAvatar2/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File ".../anaconda3/envs/GaussianAvatar2/lib/python3.8/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (3, b'ModelMat\x00'),
	result = -1
)
```
I have GLSL 1.40 installed as given by the following command
```
$ xvfb-run -a glxinfo | grep "OpenGL shading language version string"
OpenGL shading language version string: 1.40
```

**Comment by NagabhushanSN24** [comment]
I fixed the problem by overrding the OPELGL_MESA_VERSION as suggested [here](https://opencarp.org/q2a/1053/glsl-4-10-is-not-supported-error-for-meshalyzer) and [here](https://git.opencarp.org/openCARP/meshalyzer/-/issues/11)

```
export MESA_GL_VERSION_OVERRIDE=4.1
```

**Comment by FunnyGuy525** [comment]
> I fixed the problem by overrding the OPELGL_MESA_VERSION as suggested [here](https://opencarp.org/q2a/1053/glsl-4-10-is-not-supported-error-for-meshalyzer) and [here](https://git.opencarp.org/openCARP/meshalyzer/-/issues/11)
> 
> ```
> export MESA_GL_VERSION_OVERRIDE=4.1
> ```

You are my God. Thank you so much.
