### ISSUE TITLE
RuntimeError issue

### ISSUE THREAD

**Issue by slickker** [huliangxiao/GaussianAvatar#9]
Thank you for sharing your good research results.
I was interested in your research, so I ran your code.

On a PC with RTX 2080 Ti and Windows 10 and CUDA 11.8, I followed the README and installed the conda environment and diff-gaussian-rasterization and simple-knn, models and data.
It showed that there were no lpips, open3d, and pytorch3d modules, but I installed them using pip.
And I tried running the m4c_processed data set, but a runtime error occurred.

Is the Windows environment the problem? Or is it an issue with the installation process?

---------------------------------------------------------------------------------------------------------------------------------------
(gs-avatar) D:\workspace\GaussianAvatar>python train.py -s data/m4c_processed -m output/m4c_processed --train_stage 1
Optimizing output/m4c_processed
Output folder: output/m4c_processed [16/02 10:53:20]
loading smpl data  D:\workspace\GaussianAvatar\data\m4c_processed\train\smpl_parms.pth [16/02 10:53:20]
total pose length 110 [16/02 10:53:20]
Traceback (most recent call last):
  File "D:\workspace\GaussianAvatar\train.py", line 179, in <module>
    train(lp.extract(args), np.extract(args), op.extract(args), args.save_epochs, args.checkpoint_epochs)
  File "D:\workspace\GaussianAvatar\train.py", line 24, in train
    avatarmodel = AvatarModel(model, net, opt, train=True)
  File "D:\workspace\GaussianAvatar\model\avatar_model.py", line 76, in __init__
    query_points = query_map[valid_idx, :].cuda().contiguous()
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

**Comment by mxzhao** [comment]
add query_map=query_map.cuda() before the error.

**Comment by slickker** [comment]
Thanks for the advice. The error has been fixed.
